config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :users, only: %i[ index show ]
  resources :invites, only: %i[ create destroy ]

  root to: "events#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true, length: { in: 2..30 }
  validates :description, length: { maximum: 320 }

  has_many :invites
  has_many :attendees, through: :invites
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  scope :past, -> { where('date < ?', Date.today) }
  scope :future, -> { where('date >= ?', Date.today) }
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event', foreign_key: 'event_id'
  belongs_to :attendee, class_name: 'User', foreign_key: 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, inverse_of: 'creator'
  has_many :invites
  has_many :attended_events, through: :invites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
 end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [ :index ]
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:date, :title, :description, :user_id)
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def create
    event = Event.find(params[:format])
    @invite = event.invites.build
    @invite.user_id = current_user.id
    if @invite.save
      redirect_to event
    end
  end

  def destroy
    @invite = Invite.find(params[:id])
    if @invite.destroy
      redirect_to events_path
    end
  end

  private
  def invite_params
    params.require(:invite).permit(:event_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_container">
    <div class="form">
      <%= form.label :date %>
      <div class="date">
        <%= form.date_select :date %>
      </div>

      <%= form.label :title %>
      <div class="fields">
        <%= form.text_area :title %>
      </div>

      <%= form.label :description %>
      <div class="fields">
        <%= form.text_area :description %>
      </div>

      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="events">
<h1>Editing Event</h1>

<%= render 'form', event: @event %>
<p>
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</p>
</div>

app/views/events/index.html.erb
<div class="events">
  <h1>Upcoming Events</h1>
  <div class="eventbox_container">
    <% @events.future.sort_by{ |x| x.date }.each do |event| %>
      <div class="eventbox">
        <h3><%= link_to event.title, event %></h3>
        <h4><%= event.date %></h4>
        <% if user_signed_in? %>
          <% unless event.invites.any?{ |e| e.attendee == current_user } %>
            <%= link_to invites_path(event.id), method: :post, data: { confirm: 'Are you sure you wish to attend this event?' } do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
              </svg>
            <% end %>
          <% else %>
            <svg xmlns="http://www.w3.org/2000/svg" class="checkicon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
            </svg>
            <%= link_to invite_path(event.invites.find_by(attendee: current_user)), method: :delete, data: { confirm: 'Are you sure you wish to un-RSVP for this event?' } do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7a4 4 0 11-8 0 4 4 0 018 0zM9 14a6 6 0 00-6 6v1h12v-1a6 6 0 00-6-6zM21 12h-6" />
              </svg>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="events">
  <h1>New Event</h1>

  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<div class="show">
  <div>
    <h1><%= @event.title %></h1>

    <% if current_user.eql?(@event.creator) %>
      <p>
      <%= link_to 'Edit', edit_event_path(@event) %> | 
      <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>

    <p>
    <% unless @event.invites.any?{ |e| e.attendee == current_user } %>
      <%= link_to invites_path(@event.id), method: :post, data: { confirm: 'Are you sure you wish to attend this event?' } do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
        </svg>
      <% end %>
    <% else %>
      <svg xmlns="http://www.w3.org/2000/svg" class="checkicon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
      </svg>
      <%= link_to invite_path(@event.invites.find_by(attendee: current_user)), method: :delete, data: { confirm: 'Are you sure you wish to un-RSVP for this event?' } do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7a4 4 0 11-8 0 4 4 0 018 0zM9 14a6 6 0 00-6 6v1h12v-1a6 6 0 00-6-6zM21 12h-6" />
        </svg>
      <% end %>
    <% end %>
    </p>
  </div>
  <div>
    <h2>Date:</h2>
    <p>
    <%= @event.date %>
    </p>
  </div>
  <div>
    <h2>Description:</h2>
    <p class="description">
    <%= @event.description %>
    </p>
  </div>
  <div class="attends">
    <h2>Organizer:</h2>
    <p>
    <%= link_to @event.creator.username, user_path(@event.creator) %>
    </p>
  </div>
  <% unless @event.invites.empty? %>
    <div class="attends">
      <h2><%= Event.past.include?(@event) ? 'Attended:' : 'Attending:' %></h2>
      <ul>
        <% @event.invites.each do |invite| %>
          <li>
            <%= link_to invite.attendee.username, user_path(invite.attendee) %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/invites/new.html.erb
<%= form_with(model: @invite, url: invites_path) do |form| %>
  <div class="field">
    <%= form.label :attending %>
    <%= form.check_box :attending %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <header>
      <ul class="nav">
        <li class="nav_links">
          <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
          </svg>
          <%= link_to 'View All Events', events_path %>
        </li>
        <% if user_signed_in? %>
          <li class="nav_links">
            <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
            </svg>
            <%= link_to 'Create New Event', new_event_path %>
          </li>
          <li class="nav_links">
            <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
            </svg>
            <%= link_to 'View All Users', users_path %>
          </li>
          <li class="nav_links">
            <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
            </svg>
            <%= link_to 'View My Profile', current_user %>
          </li>
          <li class="nav_links">
            <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
            </svg>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li class="nav_links">
            <svg xmlns="http://www.w3.org/2000/svg" class="icons" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
            </svg>
            <%= link_to 'Sign In', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </header>

    <main> 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <footer>TGT 2021</footer>
  </body>
</html>

app/views/users/index.html.erb
<div class="events">
<h1>Users</h1>
<ul>
<% @users.each do |user| %>
  <li><%= link_to user.username, user %>; since:
  <%= user.created_at %></li>
<% end %>
</ul>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %> </h1>
<% if current_user.eql?(@user) %>
  <p>
  <%= link_to "Update account", edit_user_registration_path %>
  </p>
<% end %>
<% unless @user.events.empty? %>
  <h2>created events:</h2>
  <p>
  <% @user.events.each do |event| %>
    <%= event.date %>:
    <%= link_to event.title, event %><br>
  <% end %>
  </p>
<% end %>

<% unless @user.attended_events.future.empty? %>
  <h2>upcoming events:</h2>
  <p>
  <% @user.attended_events.future.each do |event| %>
    <%= event.date %>:
    <%= link_to event.title, event %><br>
  <% end %>
  </p>
<% end %>

<% unless @user.attended_events.past.empty? %>
  <h2>attended events:</h2>
  <p>
  <% @user.attended_events.past.each do |event| %>
    <%= event.date %>:
    <%= link_to event.title,event %><br>
  <% end %>
  </p>
<% end %>